## K-Nearest Neighbors
----------
\
**Moniele Kunrath Santos**

In [ ]:
# imports 

import pandas as pd
import numpy
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
## loading data


path = '/work/masters-degree-class-assignments/AM/KNN/'

# train datasets

X_Originais_2Features = pd.read_csv(path+'Dados_Originais_2Features/TrainingData_2F_Original.txt', delimiter='\t')
X_Normalizados_2Features = pd.read_csv(path+'Dados_Normalizados_2Features/TrainingData_2F_Norm.txt', delimiter='\t')
X_Originais_11Features = pd.read_csv(path+'Dados_Originais_11Features/TrainingData_11F_Original.txt', delimiter='\t')
X_Normalizados_11Features = pd.read_csv(path+'Dados_Normalizados_11Features/TrainingData_11F_Norm.txt', delimiter='\t')

# test datasets

Y_Originais_2Features = pd.read_csv(path+'Dados_Originais_2Features/TestingData_2F_Original.txt', delimiter='\t')
Y_Normalizados_2Features = pd.read_csv(path+'Dados_Normalizados_2Features/TestingData_2F_Norm.txt', delimiter='\t')
Y_Originais_11Features = pd.read_csv(path+'Dados_Originais_11Features/TestingData_11F_Original.txt', delimiter='\t')
Y_Normalizados_11Features = pd.read_csv(path+'Dados_Normalizados_11Features/TestingData_11F_Norm.txt', delimiter='\t')


In [ ]:
Y_Originais_11Features.head()

ID  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0  N1            6.0              0.50         0.00             1.4   
1  N2            7.2              0.41         0.30             2.1   
2  N3           10.1              0.38         0.50             2.4   
3  N4            7.8              0.48         0.68             1.7   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.057                   15                    26  0.99448  3.36   
1      0.083                   35                    72  0.99700  3.44   
2      0.104                    6                    13  0.99643  3.22   
3      0.415                   14                    32  0.99656  3.09   

   sulphates  alcohol  class  
0       0.45      9.5      0  
1       0.52      9.4      0  
2       0.65     11.6      1  
3       1.06      9.1      1

In [ ]:
X_Originais_2Features.head()

ID  total.sulfur.dioxide  citric.acid  class
0  T1                  90.0         0.38      0
1  T2                 110.0         0.30      0
2  T3                  61.0         0.41      0
3  T4                  77.5         0.00      0
4  T5                  39.0         0.35      0

In [ ]:
### Experiments

#### Experiment A

Treine modelos usando o algoritmo KNN para o conjunto de dados
**Dados_Originais_2Features**, variando o valor de k (número de vizinhos mais
próximos) entre 1, 3, 5, 7. Para cada modelo treinado, avalie seu desempenho nos
dados de teste, reportando a acurácia. 


In [ ]:
# dropping ID column

X_Originais_2Features = X_Originais_2Features.drop(['ID'], axis=1)
Y_Originais_2Features = Y_Originais_2Features.drop(['ID'], axis=1)
X_Originais_11Features = X_Originais_11Features.drop(['ID'], axis=1)
Y_Originais_11Features = Y_Originais_11Features.drop(['ID'], axis=1)
X_Normalizados_2Features = X_Normalizados_2Features.drop(['ID'], axis=1)
Y_Normalizados_2Features = Y_Normalizados_2Features.drop(['ID'], axis=1)
X_Normalizados_11Features = X_Normalizados_11Features.drop(['ID'], axis=1)
Y_Normalizados_11Features = Y_Normalizados_11Features.drop(['ID'], axis=1)

In [ ]:

# spliting the labels from exemples

# raw data
X_x = X_Originais_2Features.loc[:, X_Originais_2Features.columns != 'class']
X_y = X_Originais_2Features['class']

Y_x = Y_Originais_2Features.loc[:, Y_Originais_2Features.columns != 'class']
Y_y = Y_Originais_2Features['class']


print("Raw Data Scores: ")

for x in [1, 3, 5, 7]:
    exp_a = KNeighborsClassifier(n_neighbors=x)
    exp_a.fit(X_x, X_y)
    score = exp_a.score(Y_x, Y_y)
    print("k = "+str(x)+ " | "+str(score))



Raw Data Scores: 
k= 1 | 0.75
k= 3 | 0.5
k= 5 | 0.25
k= 7 | 0.25


Repita o procedimento com os dados **Dados_Normalizados_2Features** e compare as acurácias obtidas entre os dois modelos.

In [ ]:
# norm data
X_x = X_Normalizados_2Features.loc[:, X_Normalizados_2Features.columns != 'Class']
X_y = X_Normalizados_2Features['Class']

Y_x = Y_Normalizados_2Features.loc[:, Y_Normalizados_2Features.columns != 'Class']
Y_y = Y_Normalizados_2Features['Class']

print("Normalized Data Scores: ")

for x in [1, 3, 5, 7]:
    exp_a = KNeighborsClassifier(n_neighbors=x)
    exp_a.fit(X_x, X_y)
    score = exp_a.score(Y_x, Y_y)
    print("k = "+str(x)+ " | "+str(score))


Normalized Data Scores: 
k= 1 | 0.5
k= 3 | 0.25
k= 5 | 0.75
k= 7 | 1.0


#### Experiment B

Considerando o modelo treinado com k=5 utilizando **dados não normalizados**,
verifique quem são os k vizinhos mais próximos da instância de teste N1 (liste os
respectivos IDs). Verifique como estes vizinhos estão dispostos no espaço de
entrada em relação à instância de teste N1 e aos eixos x e y. Após tirar suas
conclusões, analise se as mesmas se aplicam às instâncias de teste N2, N3 e N4.

In [ ]:

# raw data
X_x = X_Originais_2Features.loc[:, X_Originais_2Features.columns != 'class']
X_y = X_Originais_2Features['class']

Y_x = Y_Originais_2Features.loc[:, Y_Originais_2Features.columns != 'class']
Y_y = Y_Originais_2Features['class']


exp_a = KNeighborsClassifier(n_neighbors=5)
exp_a.fit(X_x, X_y)
distances, n = exp_a.kneighbors(Y_x)

n

array([[20, 26, 29, 24, 10],
       [ 9, 36,  3, 35, 30],
       [28, 27, 14, 40, 34],
       [ 8, 25, 15, 10, 24]])

In [ ]:
# correct ID number (index+1)

n = numpy.array(n) + 1

In [ ]:
n[0]

array([21, 27, 30, 25, 11])

In [ ]:
for i in range(4):
    print("Neighbors of N"+str(i+1)+ " with IDs: \n"+str(n[i]))
    print("------------------------")

Neighbors of N1 with IDs: 
[21 27 30 25 11]
------------------------
Neighbors of N2 with IDs: 
[10 37  4 36 31]
------------------------
Neighbors of N3 with IDs: 
[29 28 15 41 35]
------------------------
Neighbors of N4 with IDs: 
[ 9 26 16 11 25]
------------------------


#### Experiment C

Treine dois modelos usando o algoritmo KNN com k=5 para os datasets
Dados_Normalizados_2Features e Dados_Normalizados_11Features.
Aplique os modelos treinados nos dados de teste, verificando os k-vizinhos mais
próximos e a classe prevista para a instância N4. 


In [ ]:
# norm data Dados_Normalizados_2Features
X_x = X_Normalizados_2Features.loc[:, X_Normalizados_2Features.columns != 'Class']
X_y = X_Normalizados_2Features['Class']

Y_x = Y_Normalizados_2Features.loc[:, Y_Normalizados_2Features.columns != 'Class']
Y_y = Y_Normalizados_2Features['Class']


exp_a = KNeighborsClassifier(n_neighbors=5)
exp_a.fit(X_x, X_y)
print("Dados_Normalizados_2Features Accuracy: ", exp_a.score(Y_x, Y_y))
distances, n = exp_a.kneighbors(Y_x)

# correct ID number (index+1)
n = numpy.array(n) + 1


print("Neighbors of N"+str(4)+ " with IDs: \n"+str(n[3]))


Dados_Normalizados_2Features Accuracy:  0.75
Neighbors of N4 with IDs: 
[32  7  8 38 30]


In [ ]:
# acerta 3/4 

# erra N4

In [ ]:
# norm data Dados_Normalizados_11Features
X_x = X_Normalizados_11Features.loc[:, X_Normalizados_11Features.columns != 'Class']
X_y = X_Normalizados_11Features['Class']

Y_x = Y_Normalizados_11Features.loc[:, Y_Normalizados_11Features.columns != 'Class']
Y_y = Y_Normalizados_11Features['Class']


exp_a = KNeighborsClassifier(n_neighbors=5)
exp_a.fit(X_x, X_y)
print("Dados_Normalizados_11Features Accuracy: ", exp_a.score(Y_x, Y_y))
distances, n = exp_a.kneighbors(Y_x)

# correct ID number (index+1)
n = numpy.array(n) + 1

print("Neighbors of N"+str(4)+ " with IDs: \n"+str(n[3]))

Dados_Normalizados_11Features Accuracy:  0.75
Neighbors of N4 with IDs: 
[30  1  8  7  6]


In [ ]:
# acerta 3/4 

# erra N4

Faça perturbações no valor do
atributo “citric acid” para a instância N4, substituindo o valor original (1.0) por 0.3
e posteriormente por 0.85 (ou seja, gere duas novas instâncias sintéticas com
esta alteração). Repita a classificação destas instâncias sintéticas com os dois
modelos (isto é, modelo baseado em 2 atributos e en 11 atributos) . Compare os
resultados, analisando como a alteração de um atributo impactou o cálculo das
distâncias euclidianas e a seleção dos k-vizinhos mais próximos em cada caso.

In [ ]:
# adding 2 more rows to the test dataset

#n5 = 0.3
#n6 = 0.85

n5 = Y_Normalizados_2Features.iloc[[3]].copy()
n6 = Y_Normalizados_2Features.iloc[[3]].copy()

In [ ]:
n5.at[3,'citric.acid']= 0.3
n6.at[3,'citric.acid']= 0.85


In [ ]:

Y_Normalizados_2Features = Y_Normalizados_2Features.append([n5, n6],ignore_index=True)

In [ ]:
Y_Normalizados_2Features

total.sulfur.dioxide  citric.acid  Class
0                 0.134        0.000      0
1                 0.496        0.441      0
2                 0.031        0.735      1
3                 0.181        1.000      1
4                 0.181        0.300      1
5                 0.181        0.850      1

In [ ]:
# norm data Dados_Normalizados_2Features
X_x = X_Normalizados_2Features.loc[:, X_Normalizados_2Features.columns != 'Class']
X_y = X_Normalizados_2Features['Class']

Y_x = Y_Normalizados_2Features.loc[:, Y_Normalizados_2Features.columns != 'Class']
Y_y = Y_Normalizados_2Features['Class']


exp_a = KNeighborsClassifier(n_neighbors=5)
exp_a.fit(X_x, X_y)
print("Dados_Normalizados_2Features Accuracy with pertubation: ", exp_a.score(Y_x, Y_y))
distances, n = exp_a.kneighbors(Y_x)

# correct ID number (index+1)
n = numpy.array(n) + 1


for i in range(4,6):
    print("Neighbors of N"+str(i+1)+ " with IDs: \n"+str(n[i]))
    print("------------------------")

Dados_Normalizados_2Features Accuracy with pertubation:  0.5
Neighbors of N5 with IDs: 
[25  9 19 20 39]
------------------------
Neighbors of N6 with IDs: 
[ 7  8 30 44 14]
------------------------


In [ ]:
n5 = Y_Normalizados_11Features.iloc[[3]].copy()
n6 = Y_Normalizados_11Features.iloc[[3]].copy()

n5.at[3,'citric.acid']= 0.3
n6.at[3,'citric.acid']= 0.85

Y_Normalizados_11Features = Y_Normalizados_11Features.append([n5, n6],ignore_index=True)

In [ ]:
# norm data Dados_Normalizados_11Features
X_x = X_Normalizados_11Features.loc[:, X_Normalizados_11Features.columns != 'Class']
X_y = X_Normalizados_11Features['Class']

Y_x = Y_Normalizados_11Features.loc[:, Y_Normalizados_11Features.columns != 'Class']
Y_y = Y_Normalizados_11Features['Class']


exp_a = KNeighborsClassifier(n_neighbors=5)
exp_a.fit(X_x, X_y)
print("Dados_Normalizados_11Features Accuracy with pertubation: ", exp_a.score(Y_x, Y_y))
distances, n = exp_a.kneighbors(Y_x)

# correct ID number (index+1)
n = numpy.array(n) + 1

for i in range(4,6):
    print("Neighbors of N"+str(i+1)+ " with IDs: \n"+str(n[i]))
    print("------------------------")

Dados_Normalizados_11Features Accuracy with pertubation:  0.5
Neighbors of N5 with IDs: 
[30  1  8  6  7]
------------------------
Neighbors of N6 with IDs: 
[30  1  8  7  6]
------------------------


In [ ]:
Y_Normalizados_11Features

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
0          0.075             0.500        0.000          -0.015      0.136   
1          0.187             0.333        0.441           0.091      0.333   
2          0.458             0.278        0.735           0.136      0.492   
3          0.243             0.463        1.000           0.030      2.848   
4          0.243             0.463        0.300           0.030      2.848   
5          0.243             0.463        0.850           0.030      2.848   

   free.sulfur.dioxide  total.sulfur.dioxide  density     pH  sulphates  \
0                0.234                 0.134    0.294  0.573      0.020   
1                0.660                 0.496    0.551  0.680      0.065   
2                0.043                 0.031    0.493  0.387      0.150   
3                0.213                 0.181    0.506  0.213      0.418   
4                0.213                 0.181    0.506  0.213      0.418   
5                0.213                 0.181    0.506  0.213      0.418   

   alcohol  Class  
0    0.156      0  
1    0.141      0  
2    0.484      1  
3    0.094      1  
4    0.094      1  
5    0.094      1

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3035cbe1-744b-40d6-9d24-00f96529caea' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>